import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn(inter.className, "bg-gray-200")}>
                <main className="flex min-h-screen flex-col items-center gap-10 py-12 px-4 sm:px-12">
                    <h1 className="text-5xl mb-4">
                        <span className="font-bold">think</span>
                        <span className="font-extralight">bridge</span>
                        <span className="max-sm:hidden"> | </span>
                        <span className="max-sm:block">Photo Gallery</span>
                    </h1>

                    {children}
                </main>
            </body>
        </html>
    );
}
